// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gift_template.proto

package dbproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GiftTemplate struct {
	Id          int64                `protobuf:"varint,1,opt,name=id" json:"id"`
	Title       string               `protobuf:"bytes,2,opt,name=title" json:"title"`
	ContentDesc string               `protobuf:"bytes,3,opt,name=content_desc,json=contentDesc" json:"content_desc"`
	Content     *GiftTemplateContent `protobuf:"bytes,4,opt,name=content" json:"content"`
	AddTime     int32                `protobuf:"varint,5,opt,name=add_time,json=addTime" json:"add_time"`
	Creator     string               `protobuf:"bytes,6,opt,name=creator" json:"creator"`
	Status      bool                 `protobuf:"varint,7,opt,name=status" json:"status"`
	ContentJson string               `protobuf:"bytes,8,opt,name=content_json,json=contentJson" json:"content_json"`
}

func (m *GiftTemplate) Reset()                    { *m = GiftTemplate{} }
func (m *GiftTemplate) String() string            { return proto.CompactTextString(m) }
func (*GiftTemplate) ProtoMessage()               {}
func (*GiftTemplate) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{0} }

func (m *GiftTemplate) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GiftTemplate) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GiftTemplate) GetContentDesc() string {
	if m != nil {
		return m.ContentDesc
	}
	return ""
}

func (m *GiftTemplate) GetContent() *GiftTemplateContent {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *GiftTemplate) GetAddTime() int32 {
	if m != nil {
		return m.AddTime
	}
	return 0
}

func (m *GiftTemplate) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *GiftTemplate) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *GiftTemplate) GetContentJson() string {
	if m != nil {
		return m.ContentJson
	}
	return ""
}

type GiftTemplateList struct {
	Page  int32           `protobuf:"varint,1,opt,name=page" json:"page"`
	Size  int32           `protobuf:"varint,2,opt,name=size" json:"size"`
	Total int32           `protobuf:"varint,3,opt,name=total" json:"total"`
	Title string          `protobuf:"bytes,4,opt,name=title" json:"title"`
	List  []*GiftTemplate `protobuf:"bytes,5,rep,name=list" json:"list"`
}

func (m *GiftTemplateList) Reset()                    { *m = GiftTemplateList{} }
func (m *GiftTemplateList) String() string            { return proto.CompactTextString(m) }
func (*GiftTemplateList) ProtoMessage()               {}
func (*GiftTemplateList) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{1} }

func (m *GiftTemplateList) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GiftTemplateList) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GiftTemplateList) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GiftTemplateList) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GiftTemplateList) GetList() []*GiftTemplate {
	if m != nil {
		return m.List
	}
	return nil
}

type GiftTemplateContent struct {
	Tickets *TicketBox  `protobuf:"bytes,1,opt,name=tickets" json:"tickets"`
	Credits *CreditsBox `protobuf:"bytes,2,opt,name=credits" json:"credits"`
}

func (m *GiftTemplateContent) Reset()                    { *m = GiftTemplateContent{} }
func (m *GiftTemplateContent) String() string            { return proto.CompactTextString(m) }
func (*GiftTemplateContent) ProtoMessage()               {}
func (*GiftTemplateContent) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{2} }

func (m *GiftTemplateContent) GetTickets() *TicketBox {
	if m != nil {
		return m.Tickets
	}
	return nil
}

func (m *GiftTemplateContent) GetCredits() *CreditsBox {
	if m != nil {
		return m.Credits
	}
	return nil
}

type TicketBox struct {
	Tickets       []*BuycaiTicket `protobuf:"bytes,1,rep,name=tickets" json:"tickets"`
	RandomTickets bool            `protobuf:"varint,2,opt,name=random_tickets,json=randomTickets" json:"random_tickets"`
	UpperLimit    int32           `protobuf:"varint,3,opt,name=upper_limit,json=upperLimit" json:"upper_limit"`
	LowerLimit    int32           `protobuf:"varint,4,opt,name=lower_limit,json=lowerLimit" json:"lower_limit"`
}

func (m *TicketBox) Reset()                    { *m = TicketBox{} }
func (m *TicketBox) String() string            { return proto.CompactTextString(m) }
func (*TicketBox) ProtoMessage()               {}
func (*TicketBox) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{3} }

func (m *TicketBox) GetTickets() []*BuycaiTicket {
	if m != nil {
		return m.Tickets
	}
	return nil
}

func (m *TicketBox) GetRandomTickets() bool {
	if m != nil {
		return m.RandomTickets
	}
	return false
}

func (m *TicketBox) GetUpperLimit() int32 {
	if m != nil {
		return m.UpperLimit
	}
	return 0
}

func (m *TicketBox) GetLowerLimit() int32 {
	if m != nil {
		return m.LowerLimit
	}
	return 0
}

type CreditsBox struct {
	Credits       int32 `protobuf:"varint,1,opt,name=credits" json:"credits"`
	RandomCredits bool  `protobuf:"varint,2,opt,name=random_credits,json=randomCredits" json:"random_credits"`
	UpperLimit    int32 `protobuf:"varint,3,opt,name=upper_limit,json=upperLimit" json:"upper_limit"`
	LowerLimit    int32 `protobuf:"varint,4,opt,name=lower_limit,json=lowerLimit" json:"lower_limit"`
}

func (m *CreditsBox) Reset()                    { *m = CreditsBox{} }
func (m *CreditsBox) String() string            { return proto.CompactTextString(m) }
func (*CreditsBox) ProtoMessage()               {}
func (*CreditsBox) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{4} }

func (m *CreditsBox) GetCredits() int32 {
	if m != nil {
		return m.Credits
	}
	return 0
}

func (m *CreditsBox) GetRandomCredits() bool {
	if m != nil {
		return m.RandomCredits
	}
	return false
}

func (m *CreditsBox) GetUpperLimit() int32 {
	if m != nil {
		return m.UpperLimit
	}
	return 0
}

func (m *CreditsBox) GetLowerLimit() int32 {
	if m != nil {
		return m.LowerLimit
	}
	return 0
}

func init() {
	proto.RegisterType((*GiftTemplate)(nil), "dbproto.GiftTemplate")
	proto.RegisterType((*GiftTemplateList)(nil), "dbproto.GiftTemplateList")
	proto.RegisterType((*GiftTemplateContent)(nil), "dbproto.GiftTemplateContent")
	proto.RegisterType((*TicketBox)(nil), "dbproto.TicketBox")
	proto.RegisterType((*CreditsBox)(nil), "dbproto.CreditsBox")
}

func init() { proto.RegisterFile("gift_template.proto", fileDescriptor15) }

var fileDescriptor15 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x99, 0xb6, 0x69, 0xba, 0x27, 0xeb, 0x22, 0x53, 0x95, 0x51, 0x04, 0x63, 0x40, 0x88,
	0xa0, 0x15, 0x2a, 0xf8, 0x00, 0xbb, 0x82, 0x20, 0x7b, 0x35, 0xf4, 0x3e, 0x64, 0x33, 0xd3, 0x65,
	0x34, 0xc9, 0x84, 0xcc, 0x29, 0xfe, 0x79, 0x09, 0xf1, 0x21, 0x7c, 0x4e, 0xa5, 0x67, 0x26, 0x69,
	0x16, 0xf6, 0xce, 0xbb, 0xf9, 0xbe, 0xfc, 0x72, 0xce, 0x97, 0x6f, 0x02, 0xeb, 0x5b, 0xb3, 0xc7,
	0x02, 0x75, 0xd3, 0xd5, 0x25, 0xea, 0x4d, 0xd7, 0x5b, 0xb4, 0x3c, 0x56, 0x37, 0x74, 0x78, 0x06,
	0xfb, 0x43, 0xab, 0xbc, 0x99, 0xfd, 0x65, 0x70, 0xfe, 0xc9, 0xec, 0x71, 0x17, 0x58, 0x7e, 0x01,
	0x33, 0xa3, 0x04, 0x4b, 0x59, 0x3e, 0x97, 0x33, 0xa3, 0xf8, 0x23, 0x88, 0xd0, 0x60, 0xad, 0xc5,
	0x2c, 0x65, 0xf9, 0x99, 0xf4, 0x82, 0xbf, 0x84, 0xf3, 0xca, 0xb6, 0xa8, 0x5b, 0x2c, 0x94, 0x76,
	0x95, 0x98, 0xd3, 0xc3, 0x24, 0x78, 0x1f, 0xb5, 0xab, 0xf8, 0x07, 0x88, 0x83, 0x14, 0x8b, 0x94,
	0xe5, 0xc9, 0xf6, 0xf9, 0x26, 0x04, 0xd8, 0x4c, 0x17, 0x5e, 0x79, 0x46, 0x0e, 0x30, 0x7f, 0x0a,
	0xab, 0x52, 0xa9, 0x02, 0x4d, 0xa3, 0x45, 0x94, 0xb2, 0x3c, 0x92, 0x71, 0xa9, 0xd4, 0xce, 0x34,
	0x9a, 0x0b, 0x88, 0xab, 0x5e, 0x97, 0x68, 0x7b, 0xb1, 0xa4, 0x85, 0x83, 0xe4, 0x4f, 0x60, 0xe9,
	0xb0, 0xc4, 0x83, 0x13, 0x71, 0xca, 0xf2, 0x95, 0x0c, 0x6a, 0x9a, 0xf3, 0x8b, 0xb3, 0xad, 0x58,
	0xdd, 0xc9, 0xf9, 0xd9, 0xd9, 0x36, 0xfb, 0xcd, 0xe0, 0xe1, 0x34, 0xd0, 0xb5, 0x71, 0xc8, 0x39,
	0x2c, 0xba, 0xf2, 0x56, 0x53, 0x0f, 0x91, 0xa4, 0xf3, 0xd1, 0x73, 0xe6, 0xa7, 0x2f, 0x22, 0x92,
	0x74, 0xa6, 0x76, 0x2c, 0x96, 0x35, 0x15, 0x10, 0x49, 0x2f, 0x4e, 0x9d, 0x2d, 0xa6, 0x9d, 0xbd,
	0x86, 0x45, 0x6d, 0x1c, 0x8a, 0x28, 0x9d, 0xe7, 0xc9, 0xf6, 0xf1, 0xbd, 0x6d, 0x48, 0x42, 0xb2,
	0x1e, 0xd6, 0xf7, 0x74, 0xc4, 0xdf, 0x40, 0x8c, 0xa6, 0xfa, 0xaa, 0xd1, 0x51, 0xb0, 0x64, 0xcb,
	0xc7, 0x21, 0x3b, 0xf2, 0x2f, 0xed, 0x77, 0x39, 0x20, 0xfc, 0x2d, 0xb5, 0xa5, 0x0c, 0x3a, 0x8a,
	0x9c, 0x6c, 0xd7, 0x23, 0x7d, 0xe5, 0x7d, 0xc2, 0x03, 0x93, 0xfd, 0x61, 0x70, 0x36, 0x4e, 0xe1,
	0xef, 0xa6, 0xab, 0xee, 0xe6, 0xbd, 0x3c, 0xfc, 0xa8, 0x4a, 0xe3, 0xd1, 0xd3, 0xb6, 0x57, 0x70,
	0xd1, 0x97, 0xad, 0xb2, 0x4d, 0x31, 0xbc, 0x37, 0xa3, 0x9b, 0x78, 0xe0, 0xdd, 0x5d, 0xc0, 0x5e,
	0x40, 0x72, 0xe8, 0x3a, 0xdd, 0x17, 0xb5, 0x69, 0x0c, 0x86, 0xda, 0x80, 0xac, 0xeb, 0xa3, 0x73,
	0x04, 0x6a, 0xfb, 0x6d, 0x04, 0x16, 0x1e, 0x20, 0x8b, 0x80, 0xec, 0x17, 0x03, 0x38, 0xe5, 0x0f,
	0xff, 0x04, 0x7d, 0xa5, 0xbf, 0xac, 0x41, 0x4e, 0x12, 0x4d, 0x6b, 0x18, 0x13, 0x85, 0x19, 0xff,
	0x9f, 0xe8, 0x66, 0x49, 0xbd, 0xbc, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x7a, 0x70, 0x9e,
	0x76, 0x03, 0x00, 0x00,
}
